robot-lab/tinkoff-web-service

predictor/views.py
templates/predictor/index.html

Remove one button processing from prediction page.

---

predictor/urls.py
predictor/views.py
templates/predictor/auth.html
templates/predictor/register.html

Added registration page with stubs for backend.

---

predictor/urls.py
predictor/views.py
templates/predictor/register.html
templates/predictor/restore.html

Added password restoring page with stubs for backend.

---

predictor/views.py
templates/predictor/auth.html
templates/predictor/index.html

Closed #31 
Indents of the fields are changed:
- Login
- Password
- File input

Fixed screens "Authorization" and "Prediction"

---

predictor/urls.py
predictor/views.py
templates/predictor/auth.html
templates/predictor/index.html
templates/predictor/research.html

The frame of the page "Research" is written.

Added "Research" page and all links are clickable

---

ml_algorithm/logger.py
ml_algorithm/ml_config.json
ml_algorithm/models/k_nearest_neighbors.py
ml_algorithm/models/linear_model.py
ml_algorithm/models/random_forest.py
ml_algorithm/parsers/config_parsers.py
ml_algorithm/parsers/linear_model_parser.py
ml_algorithm/parsers/parser.py
ml_algorithm/shell.py
ml_algorithm/tester.py
predictor/views_utils.py

Changes list:
- Update machine learning algorithm.
Сloses #40

Machine learning algorithm updated.

---

templates/predictor/index.html
templates/predictor/research.html

Close #35 
Changed size, color and position of the button on pages "Prediction" and "Research".

Fix "Logout" button

---

predictor/views.py
templates/predictor/index.html
templates/predictor/register.html
templates/predictor/research.html

Changes list:
- Added splitting users to two groups.
- Added denying to acces resarch page for not researchers.
Closes #12
Closes #15
Closes #35

Add user separation.

---

templates/predictor/auth.html
templates/predictor/register.html
templates/predictor/restore.html

- Fields "Email" renamed as "Login", it closed #46 ;
- Field "Email" leaved at pages "Registration" and "Restore" to restore password;
- Added beatiful checkbox "Is researcher" in registration form, it closed #44 .

Changed fields names

---

mlalgorithms/__init__.py
mlalgorithms/ml_config.json
mlalgorithms/models/k_nearest_neighbors.py
mlalgorithms/models/linear_model.py
mlalgorithms/models/model.py
mlalgorithms/models/random_forest.py
mlalgorithms/parsers/parser.py
mlalgorithms/shell.py
mlalgorithms/tester.py
predictor/views.py
predictor/views_utils.py

Changes list:
- Update ml_algorithm;
- Update result storrage in session;
- Fixed string convertation todo.
closes#49

Updated result presentation

---

templates/predictor/register.html
templates/predictor/research.html

Add fields:
- Password duplication
- Secret question
- Answer
Added prototype of the "Research" page.

Added new fields on the page "Register"

---

README.md
mlalgorithms/log_config.json
predictor/views.py
tinkoff_web_service/settings.py

***Cahge list:***
- Fixed readme
- Set logging settings to write to file and console.
Closses #36 
Closses #23

Add settings for users

---

templates/predictor/index.html

Added field with adding file with "Menu"

---

predictor/models.py
predictor/views.py
predictor/views_utils.py
settings_installation.py

**Changes list:**
- Added documentaion for views and models.
Closes #26
Closes #34

Added comments for views and models.

---

predictor/models.py
predictor/views.py

**Canges list:**
- Change back for registration page.
- Updated user settings model.
Closes #60

Change registrstion page

---

templates/predictor/research.html

Added fields:
- Algorithm's name and file upload
- Metric's name and file upload
- Parser's name and file upload
- Test data upload
- Debug info checkbox
Closed #5

Added fields to "Research" page

---

mlalgorithms/log_config.json
mlalgorithms/logger.py
mlalgorithms/ml_config.json
mlalgorithms/models/catboost_model.py
mlalgorithms/models/extra_trees.py
mlalgorithms/models/k_nearest_neighbors.py
mlalgorithms/models/model.py
mlalgorithms/parsers/common_parser.py
mlalgorithms/parsers/config_parsers.py
mlalgorithms/shell.py
predictor/views.py
predictor/views_utils.py
settings_installation.py

**Changes list:**
- updated ml_algorithm
- updated back for prediction page.
Closes #65

Update prediction page

---

predictor/views.py
templates/predictor/restore.html

**Change list:**
- Added restore password page.
**Closes issues**
Closes #14 
Closes #61

Page restore

---

predictor/views.py
predictor/views_utils.py

**Change list:**
- Fixed error with checking necessary fields in requests.
- Change logic of views using new check_context function.
Closes #76

Fixed error messages.

---

mlalgorithms/ml_config.json
predictor/models.py
predictor/views.py
predictor/views_utils.py
settings_installation.py

**Changes list:**
- Fixed trouble with incorrect insertions
- Fixed alarm messages
- Add saving reserchers settings.
Closes #52 
Closes #53 
Closes #76

Add researcher page

---

predictor/views.py
predictor/views_utils.py
static_delivery/admin.py
static_delivery/apps.py
static_delivery/models.py
static_delivery/tests.py
static_delivery/urls.py
static_delivery/views.py
tinkoff_web_service/settings.py
tinkoff_web_service/urls.py

**Changes list:**
- Fixed sending static files in production.
Closes #84
Closes #85

Fix static in production version.

---

templates/predictor/research.html
tinkoff_web_service/settings.py

- Fixed frontend
- Added alarm messages
Closes #93

Fix research page

---

predictor/tests.py
predictor/tests/test_auth.py
predictor/tests/test_register.py
predictor/tests/test_restore.py
predictor/views.py
predictor/views_utils.py
settings_installation.py
tinkoff_web_service/settings.py

**Change list:**
- Add tests for auth and register pages backend.
- Refactor views for auth and register page.
- Add some features wuth registrstion.
- Add generation secret key during setting up settings.
Closes #96

Add testst and refactor

---

templates/predictor/index.html
templates/predictor/research.html

If user enters file with very long name, it will be cut to display.
Closes #108

Fix bug with long file names

---

templates/predictor/index.html

Labels moved to the left side of the form.
Closes #114 
Closes #115

Fix labels and error message
